[package]
name = "riven"
version = "0.0.1"
authors = ["Mingwei Samuel <mingwei.samuel@gmail.com>"]
description = "Riot API Library (WIP)"
license = "LGPL-3.0"
edition = "2018"
exclude = [
    ".gitignore"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99"
parking_lot = { version = "0.9", features = [ "nightly" ] }
reqwest = { version = "0.10.0-alpha.1", features = [ "gzip", "json" ] }
serde = "^1.0"
tokio = "0.2.0-alpha.6"
