[package]
name = "riven"
version = "0.0.5"
authors = ["Mingwei Samuel <mingwei.samuel@gmail.com>"]
repository = "https://github.com/MingweiSamuel/Riven"
description = "Riot API Library (WIP)"
license = "LGPL-3.0"
edition = "2018"
include = [ "src/**" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
num_enum = "0.4"
parking_lot = { version = "0.9", features = [ "nightly" ] }
reqwest = { version = "0.10.0-alpha.1", features = [ "gzip", "json" ] }
scan_fmt = { version = "0.2", default-features = false }
serde = { version = "1.0", features = [ "derive" ] }
serde_repr = "0.1"
strum = "0.16"
strum_macros = "0.16"
tokio = { version = "0.2.0-alpha.6", default-features = false, features = [ "timer" ] }
url = "2.1"

[dev-dependencies]
colored = "1.8"
env_logger = "0.7"
fake_clock = { git = "https://github.com/MingweiSamuel/fake_clock", branch = "master" }
lazy_static = "1.4"
tokio = "0.2.0-alpha.6"
