[package]
name = "riven"
version = "0.0.1"
authors = ["Mingwei Samuel <mingwei.samuel@gmail.com>"]
description = "RiotApi library (wip)"
license = "LGPL-3.0"
edition = "2018"
exclude = [
    ".gitignore"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
