[package]
name = "riven_example_proxy"
version = "0.0.0"
authors = [ "Mingwei Samuel <mingwei.samuel@gmail.com>" ]
edition = "2018"

[dependencies]
riven = { path = '..' }

hyper = "0.13"
lazy_static = "1.4"
tokio = { version = "0.2", features = [ "full" ] }
