#![cfg_attr(rustfmt, rustfmt_skip)]
///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

use strum_macros::{ EnumString, EnumVariantNames, IntoStaticStr };

/// Valorant queue string IDs.
#[non_exhaustive]
#[derive(Debug, Clone)]
#[derive(Eq, PartialEq, Hash)]
#[derive(EnumString, EnumVariantNames, IntoStaticStr)]
#[repr(u8)]
pub enum ValQueue {
    /// Catch-all variant for new, unknown queue IDs.
    #[strum(default)]
    UNKNOWN(String),

    COMPETITIVE = "competitive",
    UNRATED = "unrated",
    SPIKE_RUSH = "spikerush",
    TOURNAMENT_MODE = "tournamentmode",
    DEATHMATCH = "deathmatch",
    /// One-for-all
    REPLICATION = "onefa",
    ESCALATION = "ggteam",
    TEAM_DEATHMATCH = "hurm",
    PEARL = "newmap",
    SWIFTPLAY = "swiftplay",
}

serde_strum_unknown!(ValQueue);
